//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriverService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Lessons", Namespace="http://schemas.datacontract.org/2004/07/ViewDB")]
    public partial class Lessons : DriverService.Base
    {
        
        private int CanceledField;
        
        private string DateField;
        
        private int LessonIdField;
        
        private int StudentIdField;
        
        private int TeacherIdField;
        
        private string TimeField;
        
        private bool paidField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Canceled
        {
            get
            {
                return this.CanceledField;
            }
            set
            {
                this.CanceledField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LessonId
        {
            get
            {
                return this.LessonIdField;
            }
            set
            {
                this.LessonIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StudentId
        {
            get
            {
                return this.StudentIdField;
            }
            set
            {
                this.StudentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TeacherId
        {
            get
            {
                return this.TeacherIdField;
            }
            set
            {
                this.TeacherIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Time
        {
            get
            {
                return this.TimeField;
            }
            set
            {
                this.TimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool paid
        {
            get
            {
                return this.paidField;
            }
            set
            {
                this.paidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Base", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DriverService.Course))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DriverService.CourseModule))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DriverService.Notification))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DriverService.StudentModuleProgress))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DriverService.UserInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DriverService.Calendars))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DriverService.SupportTicket))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DriverService.Chats))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DriverService.Payment))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DriverService.Lessons))]
    public partial class Base : object
    {
        
        private int IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Course", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class Course : DriverService.Base
    {
        
        private string CourseNameField;
        
        private System.DateTime CreatedDateField;
        
        private string DescriptionField;
        
        private int DisplayOrderField;
        
        private bool IsActiveField;
        
        private int TotalModulesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CourseName
        {
            get
            {
                return this.CourseNameField;
            }
            set
            {
                this.CourseNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate
        {
            get
            {
                return this.CreatedDateField;
            }
            set
            {
                this.CreatedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DisplayOrder
        {
            get
            {
                return this.DisplayOrderField;
            }
            set
            {
                this.DisplayOrderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive
        {
            get
            {
                return this.IsActiveField;
            }
            set
            {
                this.IsActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalModules
        {
            get
            {
                return this.TotalModulesField;
            }
            set
            {
                this.TotalModulesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CourseModule", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class CourseModule : DriverService.Base
    {
        
        private string ContentTypeField;
        
        private string ContentUrlField;
        
        private int CourseIdField;
        
        private System.DateTime CreatedAtField;
        
        private string DescriptionField;
        
        private int DurationMinutesField;
        
        private bool IsRequiredField;
        
        private int ModuleIdField;
        
        private string ModuleNameField;
        
        private int OrderIndexField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContentType
        {
            get
            {
                return this.ContentTypeField;
            }
            set
            {
                this.ContentTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContentUrl
        {
            get
            {
                return this.ContentUrlField;
            }
            set
            {
                this.ContentUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CourseId
        {
            get
            {
                return this.CourseIdField;
            }
            set
            {
                this.CourseIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedAt
        {
            get
            {
                return this.CreatedAtField;
            }
            set
            {
                this.CreatedAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DurationMinutes
        {
            get
            {
                return this.DurationMinutesField;
            }
            set
            {
                this.DurationMinutesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsRequired
        {
            get
            {
                return this.IsRequiredField;
            }
            set
            {
                this.IsRequiredField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ModuleId
        {
            get
            {
                return this.ModuleIdField;
            }
            set
            {
                this.ModuleIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModuleName
        {
            get
            {
                return this.ModuleNameField;
            }
            set
            {
                this.ModuleNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderIndex
        {
            get
            {
                return this.OrderIndexField;
            }
            set
            {
                this.OrderIndexField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Notification", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class Notification : DriverService.Base
    {
        
        private System.DateTime CreatedAtField;
        
        private bool IsReadField;
        
        private string MessageField;
        
        private string NotificationTypeField;
        
        private System.Nullable<System.DateTime> ReadAtField;
        
        private int RecipientIdField;
        
        private string RecipientTypeField;
        
        private int SenderIdField;
        
        private string SenderNameField;
        
        private string SenderTypeField;
        
        private string TitleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedAt
        {
            get
            {
                return this.CreatedAtField;
            }
            set
            {
                this.CreatedAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsRead
        {
            get
            {
                return this.IsReadField;
            }
            set
            {
                this.IsReadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NotificationType
        {
            get
            {
                return this.NotificationTypeField;
            }
            set
            {
                this.NotificationTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ReadAt
        {
            get
            {
                return this.ReadAtField;
            }
            set
            {
                this.ReadAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RecipientId
        {
            get
            {
                return this.RecipientIdField;
            }
            set
            {
                this.RecipientIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RecipientType
        {
            get
            {
                return this.RecipientTypeField;
            }
            set
            {
                this.RecipientTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SenderId
        {
            get
            {
                return this.SenderIdField;
            }
            set
            {
                this.SenderIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderName
        {
            get
            {
                return this.SenderNameField;
            }
            set
            {
                this.SenderNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderType
        {
            get
            {
                return this.SenderTypeField;
            }
            set
            {
                this.SenderTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StudentModuleProgress", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class StudentModuleProgress : DriverService.Base
    {
        
        private System.Nullable<System.DateTime> CompletedAtField;
        
        private int CourseIdField;
        
        private bool IsCompletedField;
        
        private int ModuleIdField;
        
        private int ProgressIdField;
        
        private int ProgressPercentField;
        
        private int StudentIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CompletedAt
        {
            get
            {
                return this.CompletedAtField;
            }
            set
            {
                this.CompletedAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CourseId
        {
            get
            {
                return this.CourseIdField;
            }
            set
            {
                this.CourseIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCompleted
        {
            get
            {
                return this.IsCompletedField;
            }
            set
            {
                this.IsCompletedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ModuleId
        {
            get
            {
                return this.ModuleIdField;
            }
            set
            {
                this.ModuleIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProgressId
        {
            get
            {
                return this.ProgressIdField;
            }
            set
            {
                this.ProgressIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProgressPercent
        {
            get
            {
                return this.ProgressPercentField;
            }
            set
            {
                this.ProgressPercentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StudentId
        {
            get
            {
                return this.StudentIdField;
            }
            set
            {
                this.StudentIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserInfo", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class UserInfo : DriverService.Base
    {
        
        private bool ConfirmedField;
        
        private int CustomLessonPriceField;
        
        private int DiscountPercentField;
        
        private string EmailField;
        
        private bool IsAdminField;
        
        private int LessonPriceField;
        
        private string LessonsField;
        
        private string PasswordField;
        
        private string PaymentMethodsField;
        
        private string PhoneField;
        
        private double RatingField;
        
        private string RatingTextField;
        
        private string RewiewField;
        
        private int StudentIdField;
        
        private int TeacherIdField;
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Confirmed
        {
            get
            {
                return this.ConfirmedField;
            }
            set
            {
                this.ConfirmedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomLessonPrice
        {
            get
            {
                return this.CustomLessonPriceField;
            }
            set
            {
                this.CustomLessonPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DiscountPercent
        {
            get
            {
                return this.DiscountPercentField;
            }
            set
            {
                this.DiscountPercentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAdmin
        {
            get
            {
                return this.IsAdminField;
            }
            set
            {
                this.IsAdminField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LessonPrice
        {
            get
            {
                return this.LessonPriceField;
            }
            set
            {
                this.LessonPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lessons
        {
            get
            {
                return this.LessonsField;
            }
            set
            {
                this.LessonsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentMethods
        {
            get
            {
                return this.PaymentMethodsField;
            }
            set
            {
                this.PaymentMethodsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Rating
        {
            get
            {
                return this.RatingField;
            }
            set
            {
                this.RatingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RatingText
        {
            get
            {
                return this.RatingTextField;
            }
            set
            {
                this.RatingTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rewiew
        {
            get
            {
                return this.RewiewField;
            }
            set
            {
                this.RewiewField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StudentId
        {
            get
            {
                return this.StudentIdField;
            }
            set
            {
                this.StudentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TeacherId
        {
            get
            {
                return this.TeacherIdField;
            }
            set
            {
                this.TeacherIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Calendars", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class Calendars : DriverService.Base
    {
        
        private bool AllDayField;
        
        private string[] AvailableDaysField;
        
        private string[] DatesUnavailableField;
        
        private string EndTimeField;
        
        private string SelectedDateField;
        
        private string SelectedDayField;
        
        private DriverService.SpecialDay[] SpecialDaysListField;
        
        private string StartTimeField;
        
        private int TeacheridField;
        
        private string UnavailableDateField;
        
        private DriverService.UnavailableDay[] UnavailableDaysField;
        
        private string[] WorkingHoursField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllDay
        {
            get
            {
                return this.AllDayField;
            }
            set
            {
                this.AllDayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] AvailableDays
        {
            get
            {
                return this.AvailableDaysField;
            }
            set
            {
                this.AvailableDaysField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] DatesUnavailable
        {
            get
            {
                return this.DatesUnavailableField;
            }
            set
            {
                this.DatesUnavailableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndTime
        {
            get
            {
                return this.EndTimeField;
            }
            set
            {
                this.EndTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SelectedDate
        {
            get
            {
                return this.SelectedDateField;
            }
            set
            {
                this.SelectedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SelectedDay
        {
            get
            {
                return this.SelectedDayField;
            }
            set
            {
                this.SelectedDayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DriverService.SpecialDay[] SpecialDaysList
        {
            get
            {
                return this.SpecialDaysListField;
            }
            set
            {
                this.SpecialDaysListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartTime
        {
            get
            {
                return this.StartTimeField;
            }
            set
            {
                this.StartTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Teacherid
        {
            get
            {
                return this.TeacheridField;
            }
            set
            {
                this.TeacheridField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnavailableDate
        {
            get
            {
                return this.UnavailableDateField;
            }
            set
            {
                this.UnavailableDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DriverService.UnavailableDay[] UnavailableDays
        {
            get
            {
                return this.UnavailableDaysField;
            }
            set
            {
                this.UnavailableDaysField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] WorkingHours
        {
            get
            {
                return this.WorkingHoursField;
            }
            set
            {
                this.WorkingHoursField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SupportTicket", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class SupportTicket : DriverService.Base
    {
        
        private string AdminNotesField;
        
        private string AssignedToField;
        
        private System.Nullable<System.DateTime> ClosedAtField;
        
        private System.DateTime CreatedAtField;
        
        private string DescriptionField;
        
        private DriverService.TicketMessage[] MessagesField;
        
        private string PriorityField;
        
        private string ResolutionField;
        
        private string StatusField;
        
        private string SubjectField;
        
        private int TicketIdField;
        
        private System.Nullable<System.DateTime> UpdatedAtField;
        
        private int UserIdField;
        
        private string UserTypeField;
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdminNotes
        {
            get
            {
                return this.AdminNotesField;
            }
            set
            {
                this.AdminNotesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AssignedTo
        {
            get
            {
                return this.AssignedToField;
            }
            set
            {
                this.AssignedToField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ClosedAt
        {
            get
            {
                return this.ClosedAtField;
            }
            set
            {
                this.ClosedAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedAt
        {
            get
            {
                return this.CreatedAtField;
            }
            set
            {
                this.CreatedAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DriverService.TicketMessage[] Messages
        {
            get
            {
                return this.MessagesField;
            }
            set
            {
                this.MessagesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Priority
        {
            get
            {
                return this.PriorityField;
            }
            set
            {
                this.PriorityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Resolution
        {
            get
            {
                return this.ResolutionField;
            }
            set
            {
                this.ResolutionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject
        {
            get
            {
                return this.SubjectField;
            }
            set
            {
                this.SubjectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TicketId
        {
            get
            {
                return this.TicketIdField;
            }
            set
            {
                this.TicketIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpdatedAt
        {
            get
            {
                return this.UpdatedAtField;
            }
            set
            {
                this.UpdatedAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserType
        {
            get
            {
                return this.UserTypeField;
            }
            set
            {
                this.UserTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Chats", Namespace="http://schemas.datacontract.org/2004/07/ViewDB")]
    public partial class Chats : DriverService.Base
    {
        
        private bool IsTeacherField;
        
        private string MessageField;
        
        private System.DateTime SentAtField;
        
        private int UserIdField;
        
        private string UsernameField;
        
        private int idField;
        
        private int studentIdField;
        
        private int teacherIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsTeacher
        {
            get
            {
                return this.IsTeacherField;
            }
            set
            {
                this.IsTeacherField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SentAt
        {
            get
            {
                return this.SentAtField;
            }
            set
            {
                this.SentAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int studentId
        {
            get
            {
                return this.studentIdField;
            }
            set
            {
                this.studentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int teacherId
        {
            get
            {
                return this.teacherIdField;
            }
            set
            {
                this.teacherIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Payment", Namespace="http://schemas.datacontract.org/2004/07/ViewDB")]
    public partial class Payment : DriverService.Base
    {
        
        private int AmountField;
        
        private int LessonIdField;
        
        private string NotesField;
        
        private int NumberOfPaymentsField;
        
        private int ParcialAmountField;
        
        private System.DateTime PaymentDateField;
        
        private int PaymentIDField;
        
        private string PaymentMethodField;
        
        private string StatusField;
        
        private int StudentIDField;
        
        private int TeacherIDField;
        
        private bool paidField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LessonId
        {
            get
            {
                return this.LessonIdField;
            }
            set
            {
                this.LessonIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Notes
        {
            get
            {
                return this.NotesField;
            }
            set
            {
                this.NotesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfPayments
        {
            get
            {
                return this.NumberOfPaymentsField;
            }
            set
            {
                this.NumberOfPaymentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParcialAmount
        {
            get
            {
                return this.ParcialAmountField;
            }
            set
            {
                this.ParcialAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PaymentDate
        {
            get
            {
                return this.PaymentDateField;
            }
            set
            {
                this.PaymentDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PaymentID
        {
            get
            {
                return this.PaymentIDField;
            }
            set
            {
                this.PaymentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentMethod
        {
            get
            {
                return this.PaymentMethodField;
            }
            set
            {
                this.PaymentMethodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StudentID
        {
            get
            {
                return this.StudentIDField;
            }
            set
            {
                this.StudentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TeacherID
        {
            get
            {
                return this.TeacherIDField;
            }
            set
            {
                this.TeacherIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool paid
        {
            get
            {
                return this.paidField;
            }
            set
            {
                this.paidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SpecialDay", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class SpecialDay : object
    {
        
        private System.DateTime DateField;
        
        private string EndTimeField;
        
        private string StartTimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndTime
        {
            get
            {
                return this.EndTimeField;
            }
            set
            {
                this.EndTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartTime
        {
            get
            {
                return this.StartTimeField;
            }
            set
            {
                this.StartTimeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnavailableDay", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class UnavailableDay : object
    {
        
        private bool AllDayField;
        
        private System.DateTime DateField;
        
        private string EndTimeField;
        
        private string StartTimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllDay
        {
            get
            {
                return this.AllDayField;
            }
            set
            {
                this.AllDayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndTime
        {
            get
            {
                return this.EndTimeField;
            }
            set
            {
                this.EndTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartTime
        {
            get
            {
                return this.StartTimeField;
            }
            set
            {
                this.StartTimeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TicketMessage", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class TicketMessage : object
    {
        
        private bool IsAdminField;
        
        private string MessageField;
        
        private int MessageIdField;
        
        private string SenderUsernameField;
        
        private System.DateTime SentAtField;
        
        private int TicketIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAdmin
        {
            get
            {
                return this.IsAdminField;
            }
            set
            {
                this.IsAdminField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MessageId
        {
            get
            {
                return this.MessageIdField;
            }
            set
            {
                this.MessageIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderUsername
        {
            get
            {
                return this.SenderUsernameField;
            }
            set
            {
                this.SenderUsernameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SentAt
        {
            get
            {
                return this.SentAtField;
            }
            set
            {
                this.SentAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TicketId
        {
            get
            {
                return this.TicketIdField;
            }
            set
            {
                this.TicketIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="AllUsers", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="UserInfo")]
    public class AllUsers : System.Collections.Generic.List<DriverService.UserInfo>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StudentCourseProgress", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class StudentCourseProgress : object
    {
        
        private int CompletedModulesField;
        
        private string CourseDescriptionField;
        
        private int CourseIdField;
        
        private string CourseNameField;
        
        private DriverService.StudentModuleProgress[] ModuleProgressField;
        
        private int ProgressPercentField;
        
        private int StudentIdField;
        
        private int TotalModulesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CompletedModules
        {
            get
            {
                return this.CompletedModulesField;
            }
            set
            {
                this.CompletedModulesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CourseDescription
        {
            get
            {
                return this.CourseDescriptionField;
            }
            set
            {
                this.CourseDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CourseId
        {
            get
            {
                return this.CourseIdField;
            }
            set
            {
                this.CourseIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CourseName
        {
            get
            {
                return this.CourseNameField;
            }
            set
            {
                this.CourseNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DriverService.StudentModuleProgress[] ModuleProgress
        {
            get
            {
                return this.ModuleProgressField;
            }
            set
            {
                this.ModuleProgressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProgressPercent
        {
            get
            {
                return this.ProgressPercentField;
            }
            set
            {
                this.ProgressPercentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StudentId
        {
            get
            {
                return this.StudentIdField;
            }
            set
            {
                this.StudentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalModules
        {
            get
            {
                return this.TotalModulesField;
            }
            set
            {
                this.TotalModulesField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DriverService.IService1")]
    public interface IService1
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CancelLesson", ReplyAction="http://tempuri.org/IService1/CancelLessonResponse")]
        System.Threading.Tasks.Task CancelLessonAsync(int lessonId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllStudentLessons", ReplyAction="http://tempuri.org/IService1/GetAllStudentLessonsResponse")]
        System.Threading.Tasks.Task<DriverService.Lessons[]> GetAllStudentLessonsAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllTeacherLessons", ReplyAction="http://tempuri.org/IService1/GetAllTeacherLessonsResponse")]
        System.Threading.Tasks.Task<DriverService.Lessons[]> GetAllTeacherLessonsAsync(int tid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddLessonForStudent", ReplyAction="http://tempuri.org/IService1/AddLessonForStudentResponse")]
        System.Threading.Tasks.Task AddLessonForStudentAsync(int sid, string Date, string time);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MarkLessonPaid", ReplyAction="http://tempuri.org/IService1/MarkLessonPaidResponse")]
        System.Threading.Tasks.Task MarkLessonPaidAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserID", ReplyAction="http://tempuri.org/IService1/GetUserIDResponse")]
        System.Threading.Tasks.Task<int> GetUserIDAsync(string username, string table);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserById", ReplyAction="http://tempuri.org/IService1/GetUserByIdResponse")]
        System.Threading.Tasks.Task<DriverService.UserInfo> GetUserByIdAsync(int id, string table);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllUsers", ReplyAction="http://tempuri.org/IService1/GetAllUsersResponse")]
        System.Threading.Tasks.Task<DriverService.AllUsers> GetAllUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllTeacher", ReplyAction="http://tempuri.org/IService1/GetAllTeacherResponse")]
        System.Threading.Tasks.Task<DriverService.AllUsers> GetAllTeacherAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckUserPassword", ReplyAction="http://tempuri.org/IService1/CheckUserPasswordResponse")]
        System.Threading.Tasks.Task<bool> CheckUserPasswordAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckUserAdmin", ReplyAction="http://tempuri.org/IService1/CheckUserAdminResponse")]
        System.Threading.Tasks.Task<bool> CheckUserAdminAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckUserExist", ReplyAction="http://tempuri.org/IService1/CheckUserExistResponse")]
        System.Threading.Tasks.Task<bool> CheckUserExistAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddUser", ReplyAction="http://tempuri.org/IService1/AddUserResponse")]
        System.Threading.Tasks.Task<bool> AddUserAsync(string name, string password, string email, string phone, bool admin, int tID, int lessonPrice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TeacherConfirm", ReplyAction="http://tempuri.org/IService1/TeacherConfirmResponse")]
        System.Threading.Tasks.Task TeacherConfirmAsync(int id, int tid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IsConfirmed", ReplyAction="http://tempuri.org/IService1/IsConfirmedResponse")]
        System.Threading.Tasks.Task<bool> IsConfirmedAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTeacherStudents", ReplyAction="http://tempuri.org/IService1/GetTeacherStudentsResponse")]
        System.Threading.Tasks.Task<DriverService.UserInfo[]> GetTeacherStudentsAsync(int tid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTeacherId", ReplyAction="http://tempuri.org/IService1/GetTeacherIdResponse")]
        System.Threading.Tasks.Task<int> GetTeacherIdAsync(int sid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateTeacherId", ReplyAction="http://tempuri.org/IService1/UpdateTeacherIdResponse")]
        System.Threading.Tasks.Task UpdateTeacherIdAsync(int sid, int tid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IsUserAdmin", ReplyAction="http://tempuri.org/IService1/IsUserAdminResponse")]
        System.Threading.Tasks.Task<bool> IsUserAdminAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetAdminStatus", ReplyAction="http://tempuri.org/IService1/SetAdminStatusResponse")]
        System.Threading.Tasks.Task SetAdminStatusAsync(int teacherId, bool isAdmin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateStudentCredentials", ReplyAction="http://tempuri.org/IService1/UpdateStudentCredentialsResponse")]
        System.Threading.Tasks.Task UpdateStudentCredentialsAsync(int studentId, string email, string phone, int teacherId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateStudentTeacher", ReplyAction="http://tempuri.org/IService1/UpdateStudentTeacherResponse")]
        System.Threading.Tasks.Task UpdateStudentTeacherAsync(int studentId, int newTeacherId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ResetPassword", ReplyAction="http://tempuri.org/IService1/ResetPasswordResponse")]
        System.Threading.Tasks.Task ResetPasswordAsync(int userId, string table, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateLessonPrice", ReplyAction="http://tempuri.org/IService1/UpdateLessonPriceResponse")]
        System.Threading.Tasks.Task UpdateLessonPriceAsync(int teacherId, int price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetStudentLessonPrice", ReplyAction="http://tempuri.org/IService1/SetStudentLessonPriceResponse")]
        System.Threading.Tasks.Task SetStudentLessonPriceAsync(int studentId, int price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStudentLessonPrice", ReplyAction="http://tempuri.org/IService1/GetStudentLessonPriceResponse")]
        System.Threading.Tasks.Task<int> GetStudentLessonPriceAsync(int studentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdatePaymentMethods", ReplyAction="http://tempuri.org/IService1/UpdatePaymentMethodsResponse")]
        System.Threading.Tasks.Task UpdatePaymentMethodsAsync(int teacherId, string paymentMethods);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTeacherCalendar", ReplyAction="http://tempuri.org/IService1/GetTeacherCalendarResponse")]
        System.Threading.Tasks.Task<DriverService.Calendars> GetTeacherCalendarAsync(int teacherId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetTeacherCalendar", ReplyAction="http://tempuri.org/IService1/SetTeacherCalendarResponse")]
        System.Threading.Tasks.Task<bool> SetTeacherCalendarAsync(DriverService.Calendars cal, int teacherId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TeacherSpacialDays", ReplyAction="http://tempuri.org/IService1/TeacherSpacialDaysResponse")]
        System.Threading.Tasks.Task<DriverService.Calendars[]> TeacherSpacialDaysAsync(int teacherId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTeacherUnavailableDates", ReplyAction="http://tempuri.org/IService1/GetTeacherUnavailableDatesResponse")]
        System.Threading.Tasks.Task<DriverService.Calendars[]> GetTeacherUnavailableDatesAsync(int teacherId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateRating", ReplyAction="http://tempuri.org/IService1/UpdateRatingResponse")]
        System.Threading.Tasks.Task UpdateRatingAsync(int tid, int rating, string rewiew);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTeacherReviews", ReplyAction="http://tempuri.org/IService1/GetTeacherReviewsResponse")]
        System.Threading.Tasks.Task<string[]> GetTeacherReviewsAsync(int tid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddMessageGlobal", ReplyAction="http://tempuri.org/IService1/AddMessageGlobalResponse")]
        System.Threading.Tasks.Task AddMessageGlobalAsync(string message, int userid, string username, bool IsTeacher);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllChatGlobal", ReplyAction="http://tempuri.org/IService1/GetAllChatGlobalResponse")]
        System.Threading.Tasks.Task<DriverService.Chats[]> GetAllChatGlobalAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetChatPrivate", ReplyAction="http://tempuri.org/IService1/GetChatPrivateResponse")]
        System.Threading.Tasks.Task<DriverService.Chats[]> GetChatPrivateAsync(int studentid, int teacherid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddMessagePrivate", ReplyAction="http://tempuri.org/IService1/AddMessagePrivateResponse")]
        System.Threading.Tasks.Task AddMessagePrivateAsync(string message, int studentid, int teacherid, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckPaid", ReplyAction="http://tempuri.org/IService1/CheckPaidResponse")]
        System.Threading.Tasks.Task<bool> CheckPaidAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Pay", ReplyAction="http://tempuri.org/IService1/PayResponse")]
        System.Threading.Tasks.Task PayAsync(DriverService.Payment payment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectPaymentByPaymentID", ReplyAction="http://tempuri.org/IService1/SelectPaymentByPaymentIDResponse")]
        System.Threading.Tasks.Task<DriverService.Payment[]> SelectPaymentByPaymentIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectPaymentByTeacherID", ReplyAction="http://tempuri.org/IService1/SelectPaymentByTeacherIDResponse")]
        System.Threading.Tasks.Task<DriverService.Payment[]> SelectPaymentByTeacherIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectPaymentByStudentID", ReplyAction="http://tempuri.org/IService1/SelectPaymentByStudentIDResponse")]
        System.Threading.Tasks.Task<DriverService.Payment[]> SelectPaymentByStudentIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTeacherIncome", ReplyAction="http://tempuri.org/IService1/GetTeacherIncomeResponse")]
        System.Threading.Tasks.Task<decimal> GetTeacherIncomeAsync(int teacherId, System.DateTime fromDate, System.DateTime toDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOutstandingPayments", ReplyAction="http://tempuri.org/IService1/GetOutstandingPaymentsResponse")]
        System.Threading.Tasks.Task<DriverService.Payment[]> GetOutstandingPaymentsAsync(int studentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOverduePayments", ReplyAction="http://tempuri.org/IService1/GetOverduePaymentsResponse")]
        System.Threading.Tasks.Task<DriverService.Payment[]> GetOverduePaymentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateSupportTicket", ReplyAction="http://tempuri.org/IService1/CreateSupportTicketResponse")]
        System.Threading.Tasks.Task<int> CreateSupportTicketAsync(DriverService.SupportTicket ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserTickets", ReplyAction="http://tempuri.org/IService1/GetUserTicketsResponse")]
        System.Threading.Tasks.Task<DriverService.SupportTicket[]> GetUserTicketsAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllTickets", ReplyAction="http://tempuri.org/IService1/GetAllTicketsResponse")]
        System.Threading.Tasks.Task<DriverService.SupportTicket[]> GetAllTicketsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTicketById", ReplyAction="http://tempuri.org/IService1/GetTicketByIdResponse")]
        System.Threading.Tasks.Task<DriverService.SupportTicket> GetTicketByIdAsync(int ticketId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateTicketStatus", ReplyAction="http://tempuri.org/IService1/UpdateTicketStatusResponse")]
        System.Threading.Tasks.Task UpdateTicketStatusAsync(int ticketId, string status, string assignedTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CloseTicket", ReplyAction="http://tempuri.org/IService1/CloseTicketResponse")]
        System.Threading.Tasks.Task CloseTicketAsync(int ticketId, string resolution, string adminNotes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddTicketMessage", ReplyAction="http://tempuri.org/IService1/AddTicketMessageResponse")]
        System.Threading.Tasks.Task AddTicketMessageAsync(DriverService.TicketMessage message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTicketMessages", ReplyAction="http://tempuri.org/IService1/GetTicketMessagesResponse")]
        System.Threading.Tasks.Task<DriverService.TicketMessage[]> GetTicketMessagesAsync(int ticketId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateTicketPriority", ReplyAction="http://tempuri.org/IService1/UpdateTicketPriorityResponse")]
        System.Threading.Tasks.Task UpdateTicketPriorityAsync(int ticketId, string priority);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MigrateAllPasswords", ReplyAction="http://tempuri.org/IService1/MigrateAllPasswordsResponse")]
        System.Threading.Tasks.Task MigrateAllPasswordsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetStudentDiscount", ReplyAction="http://tempuri.org/IService1/SetStudentDiscountResponse")]
        System.Threading.Tasks.Task SetStudentDiscountAsync(int studentId, int discountPercent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEffectiveLessonPrice", ReplyAction="http://tempuri.org/IService1/GetEffectiveLessonPriceResponse")]
        System.Threading.Tasks.Task<int> GetEffectiveLessonPriceAsync(int studentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllCourses", ReplyAction="http://tempuri.org/IService1/GetAllCoursesResponse")]
        System.Threading.Tasks.Task<DriverService.Course[]> GetAllCoursesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCourseModules", ReplyAction="http://tempuri.org/IService1/GetCourseModulesResponse")]
        System.Threading.Tasks.Task<DriverService.CourseModule[]> GetCourseModulesAsync(int courseId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStudentCourseProgress", ReplyAction="http://tempuri.org/IService1/GetStudentCourseProgressResponse")]
        System.Threading.Tasks.Task<DriverService.StudentCourseProgress[]> GetStudentCourseProgressAsync(int studentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MarkModuleComplete", ReplyAction="http://tempuri.org/IService1/MarkModuleCompleteResponse")]
        System.Threading.Tasks.Task<bool> MarkModuleCompleteAsync(int studentId, int moduleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStudentCompletedModules", ReplyAction="http://tempuri.org/IService1/GetStudentCompletedModulesResponse")]
        System.Threading.Tasks.Task<DriverService.StudentModuleProgress[]> GetStudentCompletedModulesAsync(int studentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddCourse", ReplyAction="http://tempuri.org/IService1/AddCourseResponse")]
        System.Threading.Tasks.Task<int> AddCourseAsync(DriverService.Course course);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCourse", ReplyAction="http://tempuri.org/IService1/UpdateCourseResponse")]
        System.Threading.Tasks.Task<int> UpdateCourseAsync(DriverService.Course course);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeactivateCourse", ReplyAction="http://tempuri.org/IService1/DeactivateCourseResponse")]
        System.Threading.Tasks.Task<int> DeactivateCourseAsync(int courseId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddModule", ReplyAction="http://tempuri.org/IService1/AddModuleResponse")]
        System.Threading.Tasks.Task<int> AddModuleAsync(DriverService.CourseModule module);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateModule", ReplyAction="http://tempuri.org/IService1/UpdateModuleResponse")]
        System.Threading.Tasks.Task<int> UpdateModuleAsync(DriverService.CourseModule module);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteModule", ReplyAction="http://tempuri.org/IService1/DeleteModuleResponse")]
        System.Threading.Tasks.Task<int> DeleteModuleAsync(int moduleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCourseById", ReplyAction="http://tempuri.org/IService1/GetCourseByIdResponse")]
        System.Threading.Tasks.Task<DriverService.Course> GetCourseByIdAsync(int courseId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendNotification", ReplyAction="http://tempuri.org/IService1/SendNotificationResponse")]
        System.Threading.Tasks.Task<int> SendNotificationAsync(DriverService.Notification notification);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserNotifications", ReplyAction="http://tempuri.org/IService1/GetUserNotificationsResponse")]
        System.Threading.Tasks.Task<DriverService.Notification[]> GetUserNotificationsAsync(int userId, string userType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUnreadNotificationCount", ReplyAction="http://tempuri.org/IService1/GetUnreadNotificationCountResponse")]
        System.Threading.Tasks.Task<int> GetUnreadNotificationCountAsync(int userId, string userType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUnreadNotifications", ReplyAction="http://tempuri.org/IService1/GetUnreadNotificationsResponse")]
        System.Threading.Tasks.Task<DriverService.Notification[]> GetUnreadNotificationsAsync(int userId, string userType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MarkNotificationAsRead", ReplyAction="http://tempuri.org/IService1/MarkNotificationAsReadResponse")]
        System.Threading.Tasks.Task MarkNotificationAsReadAsync(int notificationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MarkAllNotificationsAsRead", ReplyAction="http://tempuri.org/IService1/MarkAllNotificationsAsReadResponse")]
        System.Threading.Tasks.Task MarkAllNotificationsAsReadAsync(int userId, string userType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteNotification", ReplyAction="http://tempuri.org/IService1/DeleteNotificationResponse")]
        System.Threading.Tasks.Task DeleteNotificationAsync(int notificationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendTeacherMessage", ReplyAction="http://tempuri.org/IService1/SendTeacherMessageResponse")]
        System.Threading.Tasks.Task SendTeacherMessageAsync(int teacherId, string teacherName, int studentId, string title, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendStudentMessage", ReplyAction="http://tempuri.org/IService1/SendStudentMessageResponse")]
        System.Threading.Tasks.Task SendStudentMessageAsync(int studentId, string studentName, int teacherId, string title, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendLessonCancelledNotification", ReplyAction="http://tempuri.org/IService1/SendLessonCancelledNotificationResponse")]
        System.Threading.Tasks.Task SendLessonCancelledNotificationAsync(int studentId, string studentName, int teacherId, string lessonDate, string lessonTime);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IService1Channel : DriverService.IService1, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<DriverService.IService1>, DriverService.IService1
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1Client() : 
                base(Service1Client.GetDefaultBinding(), Service1Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService1.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), Service1Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task CancelLessonAsync(int lessonId)
        {
            return base.Channel.CancelLessonAsync(lessonId);
        }
        
        public System.Threading.Tasks.Task<DriverService.Lessons[]> GetAllStudentLessonsAsync(int id)
        {
            return base.Channel.GetAllStudentLessonsAsync(id);
        }
        
        public System.Threading.Tasks.Task<DriverService.Lessons[]> GetAllTeacherLessonsAsync(int tid)
        {
            return base.Channel.GetAllTeacherLessonsAsync(tid);
        }
        
        public System.Threading.Tasks.Task AddLessonForStudentAsync(int sid, string Date, string time)
        {
            return base.Channel.AddLessonForStudentAsync(sid, Date, time);
        }
        
        public System.Threading.Tasks.Task MarkLessonPaidAsync(int id)
        {
            return base.Channel.MarkLessonPaidAsync(id);
        }
        
        public System.Threading.Tasks.Task<int> GetUserIDAsync(string username, string table)
        {
            return base.Channel.GetUserIDAsync(username, table);
        }
        
        public System.Threading.Tasks.Task<DriverService.UserInfo> GetUserByIdAsync(int id, string table)
        {
            return base.Channel.GetUserByIdAsync(id, table);
        }
        
        public System.Threading.Tasks.Task<DriverService.AllUsers> GetAllUsersAsync()
        {
            return base.Channel.GetAllUsersAsync();
        }
        
        public System.Threading.Tasks.Task<DriverService.AllUsers> GetAllTeacherAsync()
        {
            return base.Channel.GetAllTeacherAsync();
        }
        
        public System.Threading.Tasks.Task<bool> CheckUserPasswordAsync(string username, string password)
        {
            return base.Channel.CheckUserPasswordAsync(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> CheckUserAdminAsync(string username)
        {
            return base.Channel.CheckUserAdminAsync(username);
        }
        
        public System.Threading.Tasks.Task<bool> CheckUserExistAsync(string username)
        {
            return base.Channel.CheckUserExistAsync(username);
        }
        
        public System.Threading.Tasks.Task<bool> AddUserAsync(string name, string password, string email, string phone, bool admin, int tID, int lessonPrice)
        {
            return base.Channel.AddUserAsync(name, password, email, phone, admin, tID, lessonPrice);
        }
        
        public System.Threading.Tasks.Task TeacherConfirmAsync(int id, int tid)
        {
            return base.Channel.TeacherConfirmAsync(id, tid);
        }
        
        public System.Threading.Tasks.Task<bool> IsConfirmedAsync(int id)
        {
            return base.Channel.IsConfirmedAsync(id);
        }
        
        public System.Threading.Tasks.Task<DriverService.UserInfo[]> GetTeacherStudentsAsync(int tid)
        {
            return base.Channel.GetTeacherStudentsAsync(tid);
        }
        
        public System.Threading.Tasks.Task<int> GetTeacherIdAsync(int sid)
        {
            return base.Channel.GetTeacherIdAsync(sid);
        }
        
        public System.Threading.Tasks.Task UpdateTeacherIdAsync(int sid, int tid)
        {
            return base.Channel.UpdateTeacherIdAsync(sid, tid);
        }
        
        public System.Threading.Tasks.Task<bool> IsUserAdminAsync(string username)
        {
            return base.Channel.IsUserAdminAsync(username);
        }
        
        public System.Threading.Tasks.Task SetAdminStatusAsync(int teacherId, bool isAdmin)
        {
            return base.Channel.SetAdminStatusAsync(teacherId, isAdmin);
        }
        
        public System.Threading.Tasks.Task UpdateStudentCredentialsAsync(int studentId, string email, string phone, int teacherId)
        {
            return base.Channel.UpdateStudentCredentialsAsync(studentId, email, phone, teacherId);
        }
        
        public System.Threading.Tasks.Task UpdateStudentTeacherAsync(int studentId, int newTeacherId)
        {
            return base.Channel.UpdateStudentTeacherAsync(studentId, newTeacherId);
        }
        
        public System.Threading.Tasks.Task ResetPasswordAsync(int userId, string table, string newPassword)
        {
            return base.Channel.ResetPasswordAsync(userId, table, newPassword);
        }
        
        public System.Threading.Tasks.Task UpdateLessonPriceAsync(int teacherId, int price)
        {
            return base.Channel.UpdateLessonPriceAsync(teacherId, price);
        }
        
        public System.Threading.Tasks.Task SetStudentLessonPriceAsync(int studentId, int price)
        {
            return base.Channel.SetStudentLessonPriceAsync(studentId, price);
        }
        
        public System.Threading.Tasks.Task<int> GetStudentLessonPriceAsync(int studentId)
        {
            return base.Channel.GetStudentLessonPriceAsync(studentId);
        }
        
        public System.Threading.Tasks.Task UpdatePaymentMethodsAsync(int teacherId, string paymentMethods)
        {
            return base.Channel.UpdatePaymentMethodsAsync(teacherId, paymentMethods);
        }
        
        public System.Threading.Tasks.Task<DriverService.Calendars> GetTeacherCalendarAsync(int teacherId)
        {
            return base.Channel.GetTeacherCalendarAsync(teacherId);
        }
        
        public System.Threading.Tasks.Task<bool> SetTeacherCalendarAsync(DriverService.Calendars cal, int teacherId)
        {
            return base.Channel.SetTeacherCalendarAsync(cal, teacherId);
        }
        
        public System.Threading.Tasks.Task<DriverService.Calendars[]> TeacherSpacialDaysAsync(int teacherId)
        {
            return base.Channel.TeacherSpacialDaysAsync(teacherId);
        }
        
        public System.Threading.Tasks.Task<DriverService.Calendars[]> GetTeacherUnavailableDatesAsync(int teacherId)
        {
            return base.Channel.GetTeacherUnavailableDatesAsync(teacherId);
        }
        
        public System.Threading.Tasks.Task UpdateRatingAsync(int tid, int rating, string rewiew)
        {
            return base.Channel.UpdateRatingAsync(tid, rating, rewiew);
        }
        
        public System.Threading.Tasks.Task<string[]> GetTeacherReviewsAsync(int tid)
        {
            return base.Channel.GetTeacherReviewsAsync(tid);
        }
        
        public System.Threading.Tasks.Task AddMessageGlobalAsync(string message, int userid, string username, bool IsTeacher)
        {
            return base.Channel.AddMessageGlobalAsync(message, userid, username, IsTeacher);
        }
        
        public System.Threading.Tasks.Task<DriverService.Chats[]> GetAllChatGlobalAsync()
        {
            return base.Channel.GetAllChatGlobalAsync();
        }
        
        public System.Threading.Tasks.Task<DriverService.Chats[]> GetChatPrivateAsync(int studentid, int teacherid)
        {
            return base.Channel.GetChatPrivateAsync(studentid, teacherid);
        }
        
        public System.Threading.Tasks.Task AddMessagePrivateAsync(string message, int studentid, int teacherid, string username)
        {
            return base.Channel.AddMessagePrivateAsync(message, studentid, teacherid, username);
        }
        
        public System.Threading.Tasks.Task<bool> CheckPaidAsync(int id)
        {
            return base.Channel.CheckPaidAsync(id);
        }
        
        public System.Threading.Tasks.Task PayAsync(DriverService.Payment payment)
        {
            return base.Channel.PayAsync(payment);
        }
        
        public System.Threading.Tasks.Task<DriverService.Payment[]> SelectPaymentByPaymentIDAsync(int id)
        {
            return base.Channel.SelectPaymentByPaymentIDAsync(id);
        }
        
        public System.Threading.Tasks.Task<DriverService.Payment[]> SelectPaymentByTeacherIDAsync(int id)
        {
            return base.Channel.SelectPaymentByTeacherIDAsync(id);
        }
        
        public System.Threading.Tasks.Task<DriverService.Payment[]> SelectPaymentByStudentIDAsync(int id)
        {
            return base.Channel.SelectPaymentByStudentIDAsync(id);
        }
        
        public System.Threading.Tasks.Task<decimal> GetTeacherIncomeAsync(int teacherId, System.DateTime fromDate, System.DateTime toDate)
        {
            return base.Channel.GetTeacherIncomeAsync(teacherId, fromDate, toDate);
        }
        
        public System.Threading.Tasks.Task<DriverService.Payment[]> GetOutstandingPaymentsAsync(int studentId)
        {
            return base.Channel.GetOutstandingPaymentsAsync(studentId);
        }
        
        public System.Threading.Tasks.Task<DriverService.Payment[]> GetOverduePaymentsAsync()
        {
            return base.Channel.GetOverduePaymentsAsync();
        }
        
        public System.Threading.Tasks.Task<int> CreateSupportTicketAsync(DriverService.SupportTicket ticket)
        {
            return base.Channel.CreateSupportTicketAsync(ticket);
        }
        
        public System.Threading.Tasks.Task<DriverService.SupportTicket[]> GetUserTicketsAsync(int userId)
        {
            return base.Channel.GetUserTicketsAsync(userId);
        }
        
        public System.Threading.Tasks.Task<DriverService.SupportTicket[]> GetAllTicketsAsync()
        {
            return base.Channel.GetAllTicketsAsync();
        }
        
        public System.Threading.Tasks.Task<DriverService.SupportTicket> GetTicketByIdAsync(int ticketId)
        {
            return base.Channel.GetTicketByIdAsync(ticketId);
        }
        
        public System.Threading.Tasks.Task UpdateTicketStatusAsync(int ticketId, string status, string assignedTo)
        {
            return base.Channel.UpdateTicketStatusAsync(ticketId, status, assignedTo);
        }
        
        public System.Threading.Tasks.Task CloseTicketAsync(int ticketId, string resolution, string adminNotes)
        {
            return base.Channel.CloseTicketAsync(ticketId, resolution, adminNotes);
        }
        
        public System.Threading.Tasks.Task AddTicketMessageAsync(DriverService.TicketMessage message)
        {
            return base.Channel.AddTicketMessageAsync(message);
        }
        
        public System.Threading.Tasks.Task<DriverService.TicketMessage[]> GetTicketMessagesAsync(int ticketId)
        {
            return base.Channel.GetTicketMessagesAsync(ticketId);
        }
        
        public System.Threading.Tasks.Task UpdateTicketPriorityAsync(int ticketId, string priority)
        {
            return base.Channel.UpdateTicketPriorityAsync(ticketId, priority);
        }
        
        public System.Threading.Tasks.Task MigrateAllPasswordsAsync()
        {
            return base.Channel.MigrateAllPasswordsAsync();
        }
        
        public System.Threading.Tasks.Task SetStudentDiscountAsync(int studentId, int discountPercent)
        {
            return base.Channel.SetStudentDiscountAsync(studentId, discountPercent);
        }
        
        public System.Threading.Tasks.Task<int> GetEffectiveLessonPriceAsync(int studentId)
        {
            return base.Channel.GetEffectiveLessonPriceAsync(studentId);
        }
        
        public System.Threading.Tasks.Task<DriverService.Course[]> GetAllCoursesAsync()
        {
            return base.Channel.GetAllCoursesAsync();
        }
        
        public System.Threading.Tasks.Task<DriverService.CourseModule[]> GetCourseModulesAsync(int courseId)
        {
            return base.Channel.GetCourseModulesAsync(courseId);
        }
        
        public System.Threading.Tasks.Task<DriverService.StudentCourseProgress[]> GetStudentCourseProgressAsync(int studentId)
        {
            return base.Channel.GetStudentCourseProgressAsync(studentId);
        }
        
        public System.Threading.Tasks.Task<bool> MarkModuleCompleteAsync(int studentId, int moduleId)
        {
            return base.Channel.MarkModuleCompleteAsync(studentId, moduleId);
        }
        
        public System.Threading.Tasks.Task<DriverService.StudentModuleProgress[]> GetStudentCompletedModulesAsync(int studentId)
        {
            return base.Channel.GetStudentCompletedModulesAsync(studentId);
        }
        
        public System.Threading.Tasks.Task<int> AddCourseAsync(DriverService.Course course)
        {
            return base.Channel.AddCourseAsync(course);
        }
        
        public System.Threading.Tasks.Task<int> UpdateCourseAsync(DriverService.Course course)
        {
            return base.Channel.UpdateCourseAsync(course);
        }
        
        public System.Threading.Tasks.Task<int> DeactivateCourseAsync(int courseId)
        {
            return base.Channel.DeactivateCourseAsync(courseId);
        }
        
        public System.Threading.Tasks.Task<int> AddModuleAsync(DriverService.CourseModule module)
        {
            return base.Channel.AddModuleAsync(module);
        }
        
        public System.Threading.Tasks.Task<int> UpdateModuleAsync(DriverService.CourseModule module)
        {
            return base.Channel.UpdateModuleAsync(module);
        }
        
        public System.Threading.Tasks.Task<int> DeleteModuleAsync(int moduleId)
        {
            return base.Channel.DeleteModuleAsync(moduleId);
        }
        
        public System.Threading.Tasks.Task<DriverService.Course> GetCourseByIdAsync(int courseId)
        {
            return base.Channel.GetCourseByIdAsync(courseId);
        }
        
        public System.Threading.Tasks.Task<int> SendNotificationAsync(DriverService.Notification notification)
        {
            return base.Channel.SendNotificationAsync(notification);
        }
        
        public System.Threading.Tasks.Task<DriverService.Notification[]> GetUserNotificationsAsync(int userId, string userType)
        {
            return base.Channel.GetUserNotificationsAsync(userId, userType);
        }
        
        public System.Threading.Tasks.Task<int> GetUnreadNotificationCountAsync(int userId, string userType)
        {
            return base.Channel.GetUnreadNotificationCountAsync(userId, userType);
        }
        
        public System.Threading.Tasks.Task<DriverService.Notification[]> GetUnreadNotificationsAsync(int userId, string userType)
        {
            return base.Channel.GetUnreadNotificationsAsync(userId, userType);
        }
        
        public System.Threading.Tasks.Task MarkNotificationAsReadAsync(int notificationId)
        {
            return base.Channel.MarkNotificationAsReadAsync(notificationId);
        }
        
        public System.Threading.Tasks.Task MarkAllNotificationsAsReadAsync(int userId, string userType)
        {
            return base.Channel.MarkAllNotificationsAsReadAsync(userId, userType);
        }
        
        public System.Threading.Tasks.Task DeleteNotificationAsync(int notificationId)
        {
            return base.Channel.DeleteNotificationAsync(notificationId);
        }
        
        public System.Threading.Tasks.Task SendTeacherMessageAsync(int teacherId, string teacherName, int studentId, string title, string message)
        {
            return base.Channel.SendTeacherMessageAsync(teacherId, teacherName, studentId, title, message);
        }
        
        public System.Threading.Tasks.Task SendStudentMessageAsync(int studentId, string studentName, int teacherId, string title, string message)
        {
            return base.Channel.SendStudentMessageAsync(studentId, studentName, teacherId, title, message);
        }
        
        public System.Threading.Tasks.Task SendLessonCancelledNotificationAsync(int studentId, string studentName, int teacherId, string lessonDate, string lessonTime)
        {
            return base.Channel.SendLessonCancelledNotificationAsync(studentId, studentName, teacherId, lessonDate, lessonTime);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/WcfServiceLibrary1/Service1/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Service1Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Service1Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService1,
        }
    }
}
