//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace driver_client.driver {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Base", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(driver_client.driver.Calendars))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(driver_client.driver.Lessons))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(driver_client.driver.Chats))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(driver_client.driver.UserInfo))]
    public partial class Base : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Calendars", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Calendars : driver_client.driver.Base {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] AvailableDaysField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] DatesUnavailableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EndTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StartTimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] AvailableDays {
            get {
                return this.AvailableDaysField;
            }
            set {
                if ((object.ReferenceEquals(this.AvailableDaysField, value) != true)) {
                    this.AvailableDaysField = value;
                    this.RaisePropertyChanged("AvailableDays");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] DatesUnavailable {
            get {
                return this.DatesUnavailableField;
            }
            set {
                if ((object.ReferenceEquals(this.DatesUnavailableField, value) != true)) {
                    this.DatesUnavailableField = value;
                    this.RaisePropertyChanged("DatesUnavailable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.EndTimeField, value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.StartTimeField, value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Lessons", Namespace="http://schemas.datacontract.org/2004/07/ViewDB")]
    [System.SerializableAttribute()]
    public partial class Lessons : driver_client.driver.Base {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LessonIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StudentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TeacherIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool paidField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date {
            get {
                return this.DateField;
            }
            set {
                if ((object.ReferenceEquals(this.DateField, value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LessonId {
            get {
                return this.LessonIdField;
            }
            set {
                if ((this.LessonIdField.Equals(value) != true)) {
                    this.LessonIdField = value;
                    this.RaisePropertyChanged("LessonId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StudentId {
            get {
                return this.StudentIdField;
            }
            set {
                if ((this.StudentIdField.Equals(value) != true)) {
                    this.StudentIdField = value;
                    this.RaisePropertyChanged("StudentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TeacherId {
            get {
                return this.TeacherIdField;
            }
            set {
                if ((this.TeacherIdField.Equals(value) != true)) {
                    this.TeacherIdField = value;
                    this.RaisePropertyChanged("TeacherId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Time {
            get {
                return this.TimeField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeField, value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool paid {
            get {
                return this.paidField;
            }
            set {
                if ((this.paidField.Equals(value) != true)) {
                    this.paidField = value;
                    this.RaisePropertyChanged("paid");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Chats", Namespace="http://schemas.datacontract.org/2004/07/ViewDB")]
    [System.SerializableAttribute()]
    public partial class Chats : driver_client.driver.Base {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsTeacherField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id1Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsTeacher {
            get {
                return this.IsTeacherField;
            }
            set {
                if ((this.IsTeacherField.Equals(value) != true)) {
                    this.IsTeacherField = value;
                    this.RaisePropertyChanged("IsTeacher");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Time {
            get {
                return this.TimeField;
            }
            set {
                if ((this.TimeField.Equals(value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="id")]
        public int id1 {
            get {
                return this.id1Field;
            }
            set {
                if ((this.id1Field.Equals(value) != true)) {
                    this.id1Field = value;
                    this.RaisePropertyChanged("id1");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserInfo", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class UserInfo : driver_client.driver.Base {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ConfirmedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LessonsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double RatingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RatingTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RewiewField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TeacherIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Confirmed {
            get {
                return this.ConfirmedField;
            }
            set {
                if ((this.ConfirmedField.Equals(value) != true)) {
                    this.ConfirmedField = value;
                    this.RaisePropertyChanged("Confirmed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAdmin {
            get {
                return this.IsAdminField;
            }
            set {
                if ((this.IsAdminField.Equals(value) != true)) {
                    this.IsAdminField = value;
                    this.RaisePropertyChanged("IsAdmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lessons {
            get {
                return this.LessonsField;
            }
            set {
                if ((object.ReferenceEquals(this.LessonsField, value) != true)) {
                    this.LessonsField = value;
                    this.RaisePropertyChanged("Lessons");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Rating {
            get {
                return this.RatingField;
            }
            set {
                if ((this.RatingField.Equals(value) != true)) {
                    this.RatingField = value;
                    this.RaisePropertyChanged("Rating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RatingText {
            get {
                return this.RatingTextField;
            }
            set {
                if ((object.ReferenceEquals(this.RatingTextField, value) != true)) {
                    this.RatingTextField = value;
                    this.RaisePropertyChanged("RatingText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rewiew {
            get {
                return this.RewiewField;
            }
            set {
                if ((object.ReferenceEquals(this.RewiewField, value) != true)) {
                    this.RewiewField = value;
                    this.RaisePropertyChanged("Rewiew");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TeacherId {
            get {
                return this.TeacherIdField;
            }
            set {
                if ((this.TeacherIdField.Equals(value) != true)) {
                    this.TeacherIdField = value;
                    this.RaisePropertyChanged("TeacherId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="AllUsers", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="UserInfo")]
    [System.SerializableAttribute()]
    public class AllUsers : System.Collections.Generic.List<driver_client.driver.UserInfo> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="driver.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserID", ReplyAction="http://tempuri.org/IService1/GetUserIDResponse")]
        int GetUserID(string username, string table);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserID", ReplyAction="http://tempuri.org/IService1/GetUserIDResponse")]
        System.Threading.Tasks.Task<int> GetUserIDAsync(string username, string table);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserById", ReplyAction="http://tempuri.org/IService1/GetUserByIdResponse")]
        driver_client.driver.UserInfo GetUserById(int id, string table);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserById", ReplyAction="http://tempuri.org/IService1/GetUserByIdResponse")]
        System.Threading.Tasks.Task<driver_client.driver.UserInfo> GetUserByIdAsync(int id, string table);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllUsers", ReplyAction="http://tempuri.org/IService1/GetAllUsersResponse")]
        driver_client.driver.AllUsers GetAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllUsers", ReplyAction="http://tempuri.org/IService1/GetAllUsersResponse")]
        System.Threading.Tasks.Task<driver_client.driver.AllUsers> GetAllUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckUserPassword", ReplyAction="http://tempuri.org/IService1/CheckUserPasswordResponse")]
        bool CheckUserPassword(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckUserPassword", ReplyAction="http://tempuri.org/IService1/CheckUserPasswordResponse")]
        System.Threading.Tasks.Task<bool> CheckUserPasswordAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckUserAdmin", ReplyAction="http://tempuri.org/IService1/CheckUserAdminResponse")]
        bool CheckUserAdmin(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckUserAdmin", ReplyAction="http://tempuri.org/IService1/CheckUserAdminResponse")]
        System.Threading.Tasks.Task<bool> CheckUserAdminAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckUserExist", ReplyAction="http://tempuri.org/IService1/CheckUserExistResponse")]
        bool CheckUserExist(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckUserExist", ReplyAction="http://tempuri.org/IService1/CheckUserExistResponse")]
        System.Threading.Tasks.Task<bool> CheckUserExistAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTeacherCalendar", ReplyAction="http://tempuri.org/IService1/GetTeacherCalendarResponse")]
        driver_client.driver.Calendars GetTeacherCalendar(int teacherId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTeacherCalendar", ReplyAction="http://tempuri.org/IService1/GetTeacherCalendarResponse")]
        System.Threading.Tasks.Task<driver_client.driver.Calendars> GetTeacherCalendarAsync(int teacherId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetTeacherCalendar", ReplyAction="http://tempuri.org/IService1/SetTeacherCalendarResponse")]
        bool SetTeacherCalendar(driver_client.driver.Calendars cal, int teacherId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetTeacherCalendar", ReplyAction="http://tempuri.org/IService1/SetTeacherCalendarResponse")]
        System.Threading.Tasks.Task<bool> SetTeacherCalendarAsync(driver_client.driver.Calendars cal, int teacherId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TeacherConfirm", ReplyAction="http://tempuri.org/IService1/TeacherConfirmResponse")]
        void TeacherConfirm(int id, int tid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TeacherConfirm", ReplyAction="http://tempuri.org/IService1/TeacherConfirmResponse")]
        System.Threading.Tasks.Task TeacherConfirmAsync(int id, int tid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllTeacher", ReplyAction="http://tempuri.org/IService1/GetAllTeacherResponse")]
        driver_client.driver.AllUsers GetAllTeacher();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllTeacher", ReplyAction="http://tempuri.org/IService1/GetAllTeacherResponse")]
        System.Threading.Tasks.Task<driver_client.driver.AllUsers> GetAllTeacherAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTeacherReviews", ReplyAction="http://tempuri.org/IService1/GetTeacherReviewsResponse")]
        string[] GetTeacherReviews(int tid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTeacherReviews", ReplyAction="http://tempuri.org/IService1/GetTeacherReviewsResponse")]
        System.Threading.Tasks.Task<string[]> GetTeacherReviewsAsync(int tid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllStudentLessons", ReplyAction="http://tempuri.org/IService1/GetAllStudentLessonsResponse")]
        driver_client.driver.Lessons[] GetAllStudentLessons(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllStudentLessons", ReplyAction="http://tempuri.org/IService1/GetAllStudentLessonsResponse")]
        System.Threading.Tasks.Task<driver_client.driver.Lessons[]> GetAllStudentLessonsAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllTeacherLessons", ReplyAction="http://tempuri.org/IService1/GetAllTeacherLessonsResponse")]
        driver_client.driver.Lessons[] GetAllTeacherLessons(int tid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllTeacherLessons", ReplyAction="http://tempuri.org/IService1/GetAllTeacherLessonsResponse")]
        System.Threading.Tasks.Task<driver_client.driver.Lessons[]> GetAllTeacherLessonsAsync(int tid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddLessonForStudent", ReplyAction="http://tempuri.org/IService1/AddLessonForStudentResponse")]
        void AddLessonForStudent(int sid, string Date, string time);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddLessonForStudent", ReplyAction="http://tempuri.org/IService1/AddLessonForStudentResponse")]
        System.Threading.Tasks.Task AddLessonForStudentAsync(int sid, string Date, string time);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateRating", ReplyAction="http://tempuri.org/IService1/UpdateRatingResponse")]
        void UpdateRating(int tid, int rating, string rewiew);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateRating", ReplyAction="http://tempuri.org/IService1/UpdateRatingResponse")]
        System.Threading.Tasks.Task UpdateRatingAsync(int tid, int rating, string rewiew);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IsConfirmed", ReplyAction="http://tempuri.org/IService1/IsConfirmedResponse")]
        bool IsConfirmed(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IsConfirmed", ReplyAction="http://tempuri.org/IService1/IsConfirmedResponse")]
        System.Threading.Tasks.Task<bool> IsConfirmedAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTeacherStudents", ReplyAction="http://tempuri.org/IService1/GetTeacherStudentsResponse")]
        driver_client.driver.UserInfo[] GetTeacherStudents(int tid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTeacherStudents", ReplyAction="http://tempuri.org/IService1/GetTeacherStudentsResponse")]
        System.Threading.Tasks.Task<driver_client.driver.UserInfo[]> GetTeacherStudentsAsync(int tid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTeacherId", ReplyAction="http://tempuri.org/IService1/GetTeacherIdResponse")]
        int GetTeacherId(int sid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTeacherId", ReplyAction="http://tempuri.org/IService1/GetTeacherIdResponse")]
        System.Threading.Tasks.Task<int> GetTeacherIdAsync(int sid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateTeacherId", ReplyAction="http://tempuri.org/IService1/UpdateTeacherIdResponse")]
        void UpdateTeacherId(int sid, int tid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateTeacherId", ReplyAction="http://tempuri.org/IService1/UpdateTeacherIdResponse")]
        System.Threading.Tasks.Task UpdateTeacherIdAsync(int sid, int tid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MarkLessonPaid", ReplyAction="http://tempuri.org/IService1/MarkLessonPaidResponse")]
        void MarkLessonPaid(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MarkLessonPaid", ReplyAction="http://tempuri.org/IService1/MarkLessonPaidResponse")]
        System.Threading.Tasks.Task MarkLessonPaidAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddMessage", ReplyAction="http://tempuri.org/IService1/AddMessageResponse")]
        void AddMessage(string message, int userid, string username, bool IsTeacher);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddMessage", ReplyAction="http://tempuri.org/IService1/AddMessageResponse")]
        System.Threading.Tasks.Task AddMessageAsync(string message, int userid, string username, bool IsTeacher);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllChat", ReplyAction="http://tempuri.org/IService1/GetAllChatResponse")]
        driver_client.driver.Chats[] GetAllChat();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllChat", ReplyAction="http://tempuri.org/IService1/GetAllChatResponse")]
        System.Threading.Tasks.Task<driver_client.driver.Chats[]> GetAllChatAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddUser", ReplyAction="http://tempuri.org/IService1/AddUserResponse")]
        bool AddUser(string name, string password, string email, string phone, bool admin, int tID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddUser", ReplyAction="http://tempuri.org/IService1/AddUserResponse")]
        System.Threading.Tasks.Task<bool> AddUserAsync(string name, string password, string email, string phone, bool admin, int tID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : driver_client.driver.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<driver_client.driver.IService1>, driver_client.driver.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetUserID(string username, string table) {
            return base.Channel.GetUserID(username, table);
        }
        
        public System.Threading.Tasks.Task<int> GetUserIDAsync(string username, string table) {
            return base.Channel.GetUserIDAsync(username, table);
        }
        
        public driver_client.driver.UserInfo GetUserById(int id, string table) {
            return base.Channel.GetUserById(id, table);
        }
        
        public System.Threading.Tasks.Task<driver_client.driver.UserInfo> GetUserByIdAsync(int id, string table) {
            return base.Channel.GetUserByIdAsync(id, table);
        }
        
        public driver_client.driver.AllUsers GetAllUsers() {
            return base.Channel.GetAllUsers();
        }
        
        public System.Threading.Tasks.Task<driver_client.driver.AllUsers> GetAllUsersAsync() {
            return base.Channel.GetAllUsersAsync();
        }
        
        public bool CheckUserPassword(string username, string password) {
            return base.Channel.CheckUserPassword(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> CheckUserPasswordAsync(string username, string password) {
            return base.Channel.CheckUserPasswordAsync(username, password);
        }
        
        public bool CheckUserAdmin(string username) {
            return base.Channel.CheckUserAdmin(username);
        }
        
        public System.Threading.Tasks.Task<bool> CheckUserAdminAsync(string username) {
            return base.Channel.CheckUserAdminAsync(username);
        }
        
        public bool CheckUserExist(string username) {
            return base.Channel.CheckUserExist(username);
        }
        
        public System.Threading.Tasks.Task<bool> CheckUserExistAsync(string username) {
            return base.Channel.CheckUserExistAsync(username);
        }
        
        public driver_client.driver.Calendars GetTeacherCalendar(int teacherId) {
            return base.Channel.GetTeacherCalendar(teacherId);
        }
        
        public System.Threading.Tasks.Task<driver_client.driver.Calendars> GetTeacherCalendarAsync(int teacherId) {
            return base.Channel.GetTeacherCalendarAsync(teacherId);
        }
        
        public bool SetTeacherCalendar(driver_client.driver.Calendars cal, int teacherId) {
            return base.Channel.SetTeacherCalendar(cal, teacherId);
        }
        
        public System.Threading.Tasks.Task<bool> SetTeacherCalendarAsync(driver_client.driver.Calendars cal, int teacherId) {
            return base.Channel.SetTeacherCalendarAsync(cal, teacherId);
        }
        
        public void TeacherConfirm(int id, int tid) {
            base.Channel.TeacherConfirm(id, tid);
        }
        
        public System.Threading.Tasks.Task TeacherConfirmAsync(int id, int tid) {
            return base.Channel.TeacherConfirmAsync(id, tid);
        }
        
        public driver_client.driver.AllUsers GetAllTeacher() {
            return base.Channel.GetAllTeacher();
        }
        
        public System.Threading.Tasks.Task<driver_client.driver.AllUsers> GetAllTeacherAsync() {
            return base.Channel.GetAllTeacherAsync();
        }
        
        public string[] GetTeacherReviews(int tid) {
            return base.Channel.GetTeacherReviews(tid);
        }
        
        public System.Threading.Tasks.Task<string[]> GetTeacherReviewsAsync(int tid) {
            return base.Channel.GetTeacherReviewsAsync(tid);
        }
        
        public driver_client.driver.Lessons[] GetAllStudentLessons(int id) {
            return base.Channel.GetAllStudentLessons(id);
        }
        
        public System.Threading.Tasks.Task<driver_client.driver.Lessons[]> GetAllStudentLessonsAsync(int id) {
            return base.Channel.GetAllStudentLessonsAsync(id);
        }
        
        public driver_client.driver.Lessons[] GetAllTeacherLessons(int tid) {
            return base.Channel.GetAllTeacherLessons(tid);
        }
        
        public System.Threading.Tasks.Task<driver_client.driver.Lessons[]> GetAllTeacherLessonsAsync(int tid) {
            return base.Channel.GetAllTeacherLessonsAsync(tid);
        }
        
        public void AddLessonForStudent(int sid, string Date, string time) {
            base.Channel.AddLessonForStudent(sid, Date, time);
        }
        
        public System.Threading.Tasks.Task AddLessonForStudentAsync(int sid, string Date, string time) {
            return base.Channel.AddLessonForStudentAsync(sid, Date, time);
        }
        
        public void UpdateRating(int tid, int rating, string rewiew) {
            base.Channel.UpdateRating(tid, rating, rewiew);
        }
        
        public System.Threading.Tasks.Task UpdateRatingAsync(int tid, int rating, string rewiew) {
            return base.Channel.UpdateRatingAsync(tid, rating, rewiew);
        }
        
        public bool IsConfirmed(int id) {
            return base.Channel.IsConfirmed(id);
        }
        
        public System.Threading.Tasks.Task<bool> IsConfirmedAsync(int id) {
            return base.Channel.IsConfirmedAsync(id);
        }
        
        public driver_client.driver.UserInfo[] GetTeacherStudents(int tid) {
            return base.Channel.GetTeacherStudents(tid);
        }
        
        public System.Threading.Tasks.Task<driver_client.driver.UserInfo[]> GetTeacherStudentsAsync(int tid) {
            return base.Channel.GetTeacherStudentsAsync(tid);
        }
        
        public int GetTeacherId(int sid) {
            return base.Channel.GetTeacherId(sid);
        }
        
        public System.Threading.Tasks.Task<int> GetTeacherIdAsync(int sid) {
            return base.Channel.GetTeacherIdAsync(sid);
        }
        
        public void UpdateTeacherId(int sid, int tid) {
            base.Channel.UpdateTeacherId(sid, tid);
        }
        
        public System.Threading.Tasks.Task UpdateTeacherIdAsync(int sid, int tid) {
            return base.Channel.UpdateTeacherIdAsync(sid, tid);
        }
        
        public void MarkLessonPaid(int id) {
            base.Channel.MarkLessonPaid(id);
        }
        
        public System.Threading.Tasks.Task MarkLessonPaidAsync(int id) {
            return base.Channel.MarkLessonPaidAsync(id);
        }
        
        public void AddMessage(string message, int userid, string username, bool IsTeacher) {
            base.Channel.AddMessage(message, userid, username, IsTeacher);
        }
        
        public System.Threading.Tasks.Task AddMessageAsync(string message, int userid, string username, bool IsTeacher) {
            return base.Channel.AddMessageAsync(message, userid, username, IsTeacher);
        }
        
        public driver_client.driver.Chats[] GetAllChat() {
            return base.Channel.GetAllChat();
        }
        
        public System.Threading.Tasks.Task<driver_client.driver.Chats[]> GetAllChatAsync() {
            return base.Channel.GetAllChatAsync();
        }
        
        public bool AddUser(string name, string password, string email, string phone, bool admin, int tID) {
            return base.Channel.AddUser(name, password, email, phone, admin, tID);
        }
        
        public System.Threading.Tasks.Task<bool> AddUserAsync(string name, string password, string email, string phone, bool admin, int tID) {
            return base.Channel.AddUserAsync(name, password, email, phone, admin, tID);
        }
    }
}
