//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webTOsrv
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Base", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(webTOsrv.Calendars))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(webTOsrv.Lessons))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(webTOsrv.Chats))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(webTOsrv.Payment))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(webTOsrv.UserInfo))]
    public partial class Base : object
    {
        
        private int IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Calendars", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class Calendars : webTOsrv.Base
    {
        
        private bool AllDayField;
        
        private string[] AvailableDaysField;
        
        private string[] DatesUnavailableField;
        
        private string EndTimeField;
        
        private string SelectedDateField;
        
        private string SelectedDayField;
        
        private webTOsrv.SpecialDay[] SpecialDaysListField;
        
        private string StartTimeField;
        
        private int TeacheridField;
        
        private string UnavailableDateField;
        
        private webTOsrv.UnavailableDay[] UnavailableDaysField;
        
        private string[] WorkingHoursField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllDay
        {
            get
            {
                return this.AllDayField;
            }
            set
            {
                this.AllDayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] AvailableDays
        {
            get
            {
                return this.AvailableDaysField;
            }
            set
            {
                this.AvailableDaysField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] DatesUnavailable
        {
            get
            {
                return this.DatesUnavailableField;
            }
            set
            {
                this.DatesUnavailableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndTime
        {
            get
            {
                return this.EndTimeField;
            }
            set
            {
                this.EndTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SelectedDate
        {
            get
            {
                return this.SelectedDateField;
            }
            set
            {
                this.SelectedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SelectedDay
        {
            get
            {
                return this.SelectedDayField;
            }
            set
            {
                this.SelectedDayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public webTOsrv.SpecialDay[] SpecialDaysList
        {
            get
            {
                return this.SpecialDaysListField;
            }
            set
            {
                this.SpecialDaysListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartTime
        {
            get
            {
                return this.StartTimeField;
            }
            set
            {
                this.StartTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Teacherid
        {
            get
            {
                return this.TeacheridField;
            }
            set
            {
                this.TeacheridField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnavailableDate
        {
            get
            {
                return this.UnavailableDateField;
            }
            set
            {
                this.UnavailableDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public webTOsrv.UnavailableDay[] UnavailableDays
        {
            get
            {
                return this.UnavailableDaysField;
            }
            set
            {
                this.UnavailableDaysField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] WorkingHours
        {
            get
            {
                return this.WorkingHoursField;
            }
            set
            {
                this.WorkingHoursField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Lessons", Namespace="http://schemas.datacontract.org/2004/07/ViewDB")]
    public partial class Lessons : webTOsrv.Base
    {
        
        private string DateField;
        
        private int LessonIdField;
        
        private int StudentIdField;
        
        private int TeacherIdField;
        
        private string TimeField;
        
        private bool paidField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LessonId
        {
            get
            {
                return this.LessonIdField;
            }
            set
            {
                this.LessonIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StudentId
        {
            get
            {
                return this.StudentIdField;
            }
            set
            {
                this.StudentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TeacherId
        {
            get
            {
                return this.TeacherIdField;
            }
            set
            {
                this.TeacherIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Time
        {
            get
            {
                return this.TimeField;
            }
            set
            {
                this.TimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool paid
        {
            get
            {
                return this.paidField;
            }
            set
            {
                this.paidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Chats", Namespace="http://schemas.datacontract.org/2004/07/ViewDB")]
    public partial class Chats : webTOsrv.Base
    {
        
        private bool IsTeacherField;
        
        private string MessageField;
        
        private System.DateTime SentAtField;
        
        private int UserIdField;
        
        private string UsernameField;
        
        private int idField;
        
        private int studentIdField;
        
        private int teacherIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsTeacher
        {
            get
            {
                return this.IsTeacherField;
            }
            set
            {
                this.IsTeacherField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SentAt
        {
            get
            {
                return this.SentAtField;
            }
            set
            {
                this.SentAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int studentId
        {
            get
            {
                return this.studentIdField;
            }
            set
            {
                this.studentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int teacherId
        {
            get
            {
                return this.teacherIdField;
            }
            set
            {
                this.teacherIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Payment", Namespace="http://schemas.datacontract.org/2004/07/ViewDB")]
    public partial class Payment : webTOsrv.Base
    {
        
        private int AmountField;
        
        private int NumberOfPaymentsField;
        
        private int ParcialAmountField;
        
        private System.DateTime PaymentDateField;
        
        private int PaymentIDField;
        
        private string PaymentMethodField;
        
        private int StudentIDField;
        
        private int TeacherIDField;
        
        private bool paidField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfPayments
        {
            get
            {
                return this.NumberOfPaymentsField;
            }
            set
            {
                this.NumberOfPaymentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParcialAmount
        {
            get
            {
                return this.ParcialAmountField;
            }
            set
            {
                this.ParcialAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PaymentDate
        {
            get
            {
                return this.PaymentDateField;
            }
            set
            {
                this.PaymentDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PaymentID
        {
            get
            {
                return this.PaymentIDField;
            }
            set
            {
                this.PaymentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentMethod
        {
            get
            {
                return this.PaymentMethodField;
            }
            set
            {
                this.PaymentMethodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StudentID
        {
            get
            {
                return this.StudentIDField;
            }
            set
            {
                this.StudentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TeacherID
        {
            get
            {
                return this.TeacherIDField;
            }
            set
            {
                this.TeacherIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool paid
        {
            get
            {
                return this.paidField;
            }
            set
            {
                this.paidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserInfo", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class UserInfo : webTOsrv.Base
    {
        
        private bool ConfirmedField;
        
        private string EmailField;
        
        private bool IsAdminField;
        
        private string LessonsField;
        
        private string PasswordField;
        
        private string PhoneField;
        
        private double RatingField;
        
        private string RatingTextField;
        
        private string RewiewField;
        
        private int TeacherIdField;
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Confirmed
        {
            get
            {
                return this.ConfirmedField;
            }
            set
            {
                this.ConfirmedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAdmin
        {
            get
            {
                return this.IsAdminField;
            }
            set
            {
                this.IsAdminField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lessons
        {
            get
            {
                return this.LessonsField;
            }
            set
            {
                this.LessonsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Rating
        {
            get
            {
                return this.RatingField;
            }
            set
            {
                this.RatingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RatingText
        {
            get
            {
                return this.RatingTextField;
            }
            set
            {
                this.RatingTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rewiew
        {
            get
            {
                return this.RewiewField;
            }
            set
            {
                this.RewiewField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TeacherId
        {
            get
            {
                return this.TeacherIdField;
            }
            set
            {
                this.TeacherIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SpecialDay", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class SpecialDay : object
    {
        
        private System.DateTime DateField;
        
        private string EndTimeField;
        
        private string StartTimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndTime
        {
            get
            {
                return this.EndTimeField;
            }
            set
            {
                this.EndTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartTime
        {
            get
            {
                return this.StartTimeField;
            }
            set
            {
                this.StartTimeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnavailableDay", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class UnavailableDay : object
    {
        
        private bool AllDayField;
        
        private System.DateTime DateField;
        
        private string EndTimeField;
        
        private string StartTimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllDay
        {
            get
            {
                return this.AllDayField;
            }
            set
            {
                this.AllDayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndTime
        {
            get
            {
                return this.EndTimeField;
            }
            set
            {
                this.EndTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartTime
        {
            get
            {
                return this.StartTimeField;
            }
            set
            {
                this.StartTimeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="AllUsers", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="UserInfo")]
    public class AllUsers : System.Collections.Generic.List<webTOsrv.UserInfo>
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="webTOsrv.IService1")]
    public interface IService1
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserID", ReplyAction="http://tempuri.org/IService1/GetUserIDResponse")]
        int GetUserID(string username, string table);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserID", ReplyAction="http://tempuri.org/IService1/GetUserIDResponse")]
        System.Threading.Tasks.Task<int> GetUserIDAsync(string username, string table);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserById", ReplyAction="http://tempuri.org/IService1/GetUserByIdResponse")]
        webTOsrv.UserInfo GetUserById(int id, string table);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserById", ReplyAction="http://tempuri.org/IService1/GetUserByIdResponse")]
        System.Threading.Tasks.Task<webTOsrv.UserInfo> GetUserByIdAsync(int id, string table);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllUsers", ReplyAction="http://tempuri.org/IService1/GetAllUsersResponse")]
        webTOsrv.AllUsers GetAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllUsers", ReplyAction="http://tempuri.org/IService1/GetAllUsersResponse")]
        System.Threading.Tasks.Task<webTOsrv.AllUsers> GetAllUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckUserPassword", ReplyAction="http://tempuri.org/IService1/CheckUserPasswordResponse")]
        bool CheckUserPassword(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckUserPassword", ReplyAction="http://tempuri.org/IService1/CheckUserPasswordResponse")]
        System.Threading.Tasks.Task<bool> CheckUserPasswordAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckUserAdmin", ReplyAction="http://tempuri.org/IService1/CheckUserAdminResponse")]
        bool CheckUserAdmin(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckUserAdmin", ReplyAction="http://tempuri.org/IService1/CheckUserAdminResponse")]
        System.Threading.Tasks.Task<bool> CheckUserAdminAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckUserExist", ReplyAction="http://tempuri.org/IService1/CheckUserExistResponse")]
        bool CheckUserExist(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckUserExist", ReplyAction="http://tempuri.org/IService1/CheckUserExistResponse")]
        System.Threading.Tasks.Task<bool> CheckUserExistAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTeacherCalendar", ReplyAction="http://tempuri.org/IService1/GetTeacherCalendarResponse")]
        webTOsrv.Calendars GetTeacherCalendar(int teacherId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTeacherCalendar", ReplyAction="http://tempuri.org/IService1/GetTeacherCalendarResponse")]
        System.Threading.Tasks.Task<webTOsrv.Calendars> GetTeacherCalendarAsync(int teacherId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetTeacherCalendar", ReplyAction="http://tempuri.org/IService1/SetTeacherCalendarResponse")]
        bool SetTeacherCalendar(webTOsrv.Calendars cal, int teacherId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetTeacherCalendar", ReplyAction="http://tempuri.org/IService1/SetTeacherCalendarResponse")]
        System.Threading.Tasks.Task<bool> SetTeacherCalendarAsync(webTOsrv.Calendars cal, int teacherId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TeacherConfirm", ReplyAction="http://tempuri.org/IService1/TeacherConfirmResponse")]
        void TeacherConfirm(int id, int tid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TeacherConfirm", ReplyAction="http://tempuri.org/IService1/TeacherConfirmResponse")]
        System.Threading.Tasks.Task TeacherConfirmAsync(int id, int tid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllTeacher", ReplyAction="http://tempuri.org/IService1/GetAllTeacherResponse")]
        webTOsrv.AllUsers GetAllTeacher();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllTeacher", ReplyAction="http://tempuri.org/IService1/GetAllTeacherResponse")]
        System.Threading.Tasks.Task<webTOsrv.AllUsers> GetAllTeacherAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTeacherReviews", ReplyAction="http://tempuri.org/IService1/GetTeacherReviewsResponse")]
        string[] GetTeacherReviews(int tid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTeacherReviews", ReplyAction="http://tempuri.org/IService1/GetTeacherReviewsResponse")]
        System.Threading.Tasks.Task<string[]> GetTeacherReviewsAsync(int tid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllStudentLessons", ReplyAction="http://tempuri.org/IService1/GetAllStudentLessonsResponse")]
        webTOsrv.Lessons[] GetAllStudentLessons(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllStudentLessons", ReplyAction="http://tempuri.org/IService1/GetAllStudentLessonsResponse")]
        System.Threading.Tasks.Task<webTOsrv.Lessons[]> GetAllStudentLessonsAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllTeacherLessons", ReplyAction="http://tempuri.org/IService1/GetAllTeacherLessonsResponse")]
        webTOsrv.Lessons[] GetAllTeacherLessons(int tid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllTeacherLessons", ReplyAction="http://tempuri.org/IService1/GetAllTeacherLessonsResponse")]
        System.Threading.Tasks.Task<webTOsrv.Lessons[]> GetAllTeacherLessonsAsync(int tid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddLessonForStudent", ReplyAction="http://tempuri.org/IService1/AddLessonForStudentResponse")]
        void AddLessonForStudent(int sid, string Date, string time);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddLessonForStudent", ReplyAction="http://tempuri.org/IService1/AddLessonForStudentResponse")]
        System.Threading.Tasks.Task AddLessonForStudentAsync(int sid, string Date, string time);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateRating", ReplyAction="http://tempuri.org/IService1/UpdateRatingResponse")]
        void UpdateRating(int tid, int rating, string rewiew);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateRating", ReplyAction="http://tempuri.org/IService1/UpdateRatingResponse")]
        System.Threading.Tasks.Task UpdateRatingAsync(int tid, int rating, string rewiew);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IsConfirmed", ReplyAction="http://tempuri.org/IService1/IsConfirmedResponse")]
        bool IsConfirmed(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IsConfirmed", ReplyAction="http://tempuri.org/IService1/IsConfirmedResponse")]
        System.Threading.Tasks.Task<bool> IsConfirmedAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTeacherStudents", ReplyAction="http://tempuri.org/IService1/GetTeacherStudentsResponse")]
        webTOsrv.UserInfo[] GetTeacherStudents(int tid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTeacherStudents", ReplyAction="http://tempuri.org/IService1/GetTeacherStudentsResponse")]
        System.Threading.Tasks.Task<webTOsrv.UserInfo[]> GetTeacherStudentsAsync(int tid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTeacherId", ReplyAction="http://tempuri.org/IService1/GetTeacherIdResponse")]
        int GetTeacherId(int sid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTeacherId", ReplyAction="http://tempuri.org/IService1/GetTeacherIdResponse")]
        System.Threading.Tasks.Task<int> GetTeacherIdAsync(int sid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateTeacherId", ReplyAction="http://tempuri.org/IService1/UpdateTeacherIdResponse")]
        void UpdateTeacherId(int sid, int tid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateTeacherId", ReplyAction="http://tempuri.org/IService1/UpdateTeacherIdResponse")]
        System.Threading.Tasks.Task UpdateTeacherIdAsync(int sid, int tid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MarkLessonPaid", ReplyAction="http://tempuri.org/IService1/MarkLessonPaidResponse")]
        void MarkLessonPaid(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MarkLessonPaid", ReplyAction="http://tempuri.org/IService1/MarkLessonPaidResponse")]
        System.Threading.Tasks.Task MarkLessonPaidAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddMessageGlobal", ReplyAction="http://tempuri.org/IService1/AddMessageGlobalResponse")]
        void AddMessageGlobal(string message, int userid, string username, bool IsTeacher);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddMessageGlobal", ReplyAction="http://tempuri.org/IService1/AddMessageGlobalResponse")]
        System.Threading.Tasks.Task AddMessageGlobalAsync(string message, int userid, string username, bool IsTeacher);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllChatGlobal", ReplyAction="http://tempuri.org/IService1/GetAllChatGlobalResponse")]
        webTOsrv.Chats[] GetAllChatGlobal();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllChatGlobal", ReplyAction="http://tempuri.org/IService1/GetAllChatGlobalResponse")]
        System.Threading.Tasks.Task<webTOsrv.Chats[]> GetAllChatGlobalAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetChatPrivate", ReplyAction="http://tempuri.org/IService1/GetChatPrivateResponse")]
        webTOsrv.Chats[] GetChatPrivate(int studentid, int teacherid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetChatPrivate", ReplyAction="http://tempuri.org/IService1/GetChatPrivateResponse")]
        System.Threading.Tasks.Task<webTOsrv.Chats[]> GetChatPrivateAsync(int studentid, int teacherid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddMessagePrivate", ReplyAction="http://tempuri.org/IService1/AddMessagePrivateResponse")]
        void AddMessagePrivate(string message, int studentid, int teacherid, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddMessagePrivate", ReplyAction="http://tempuri.org/IService1/AddMessagePrivateResponse")]
        System.Threading.Tasks.Task AddMessagePrivateAsync(string message, int studentid, int teacherid, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckPaid", ReplyAction="http://tempuri.org/IService1/CheckPaidResponse")]
        bool CheckPaid(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckPaid", ReplyAction="http://tempuri.org/IService1/CheckPaidResponse")]
        System.Threading.Tasks.Task<bool> CheckPaidAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Pay", ReplyAction="http://tempuri.org/IService1/PayResponse")]
        void Pay(webTOsrv.Payment payment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Pay", ReplyAction="http://tempuri.org/IService1/PayResponse")]
        System.Threading.Tasks.Task PayAsync(webTOsrv.Payment payment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectPaymentByPaymentID", ReplyAction="http://tempuri.org/IService1/SelectPaymentByPaymentIDResponse")]
        webTOsrv.Payment[] SelectPaymentByPaymentID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectPaymentByPaymentID", ReplyAction="http://tempuri.org/IService1/SelectPaymentByPaymentIDResponse")]
        System.Threading.Tasks.Task<webTOsrv.Payment[]> SelectPaymentByPaymentIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectPaymentByTeacherID", ReplyAction="http://tempuri.org/IService1/SelectPaymentByTeacherIDResponse")]
        webTOsrv.Payment[] SelectPaymentByTeacherID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectPaymentByTeacherID", ReplyAction="http://tempuri.org/IService1/SelectPaymentByTeacherIDResponse")]
        System.Threading.Tasks.Task<webTOsrv.Payment[]> SelectPaymentByTeacherIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TeacherSpacialDays", ReplyAction="http://tempuri.org/IService1/TeacherSpacialDaysResponse")]
        webTOsrv.Calendars[] TeacherSpacialDays(int teacherId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TeacherSpacialDays", ReplyAction="http://tempuri.org/IService1/TeacherSpacialDaysResponse")]
        System.Threading.Tasks.Task<webTOsrv.Calendars[]> TeacherSpacialDaysAsync(int teacherId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTeacherUnavailableDates", ReplyAction="http://tempuri.org/IService1/GetTeacherUnavailableDatesResponse")]
        webTOsrv.Calendars[] GetTeacherUnavailableDates(int teacherId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTeacherUnavailableDates", ReplyAction="http://tempuri.org/IService1/GetTeacherUnavailableDatesResponse")]
        System.Threading.Tasks.Task<webTOsrv.Calendars[]> GetTeacherUnavailableDatesAsync(int teacherId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddUser", ReplyAction="http://tempuri.org/IService1/AddUserResponse")]
        bool AddUser(string name, string password, string email, string phone, bool admin, int tID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddUser", ReplyAction="http://tempuri.org/IService1/AddUserResponse")]
        System.Threading.Tasks.Task<bool> AddUserAsync(string name, string password, string email, string phone, bool admin, int tID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectPaymentByStudentID", ReplyAction="http://tempuri.org/IService1/SelectPaymentByStudentIDResponse")]
        webTOsrv.Payment[] SelectPaymentByStudentID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectPaymentByStudentID", ReplyAction="http://tempuri.org/IService1/SelectPaymentByStudentIDResponse")]
        System.Threading.Tasks.Task<webTOsrv.Payment[]> SelectPaymentByStudentIDAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IService1Channel : webTOsrv.IService1, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<webTOsrv.IService1>, webTOsrv.IService1
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1Client() : 
                base(Service1Client.GetDefaultBinding(), Service1Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService1.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), Service1Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public int GetUserID(string username, string table)
        {
            return base.Channel.GetUserID(username, table);
        }
        
        public System.Threading.Tasks.Task<int> GetUserIDAsync(string username, string table)
        {
            return base.Channel.GetUserIDAsync(username, table);
        }
        
        public webTOsrv.UserInfo GetUserById(int id, string table)
        {
            return base.Channel.GetUserById(id, table);
        }
        
        public System.Threading.Tasks.Task<webTOsrv.UserInfo> GetUserByIdAsync(int id, string table)
        {
            return base.Channel.GetUserByIdAsync(id, table);
        }
        
        public webTOsrv.AllUsers GetAllUsers()
        {
            return base.Channel.GetAllUsers();
        }
        
        public System.Threading.Tasks.Task<webTOsrv.AllUsers> GetAllUsersAsync()
        {
            return base.Channel.GetAllUsersAsync();
        }
        
        public bool CheckUserPassword(string username, string password)
        {
            return base.Channel.CheckUserPassword(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> CheckUserPasswordAsync(string username, string password)
        {
            return base.Channel.CheckUserPasswordAsync(username, password);
        }
        
        public bool CheckUserAdmin(string username)
        {
            return base.Channel.CheckUserAdmin(username);
        }
        
        public System.Threading.Tasks.Task<bool> CheckUserAdminAsync(string username)
        {
            return base.Channel.CheckUserAdminAsync(username);
        }
        
        public bool CheckUserExist(string username)
        {
            return base.Channel.CheckUserExist(username);
        }
        
        public System.Threading.Tasks.Task<bool> CheckUserExistAsync(string username)
        {
            return base.Channel.CheckUserExistAsync(username);
        }
        
        public webTOsrv.Calendars GetTeacherCalendar(int teacherId)
        {
            return base.Channel.GetTeacherCalendar(teacherId);
        }
        
        public System.Threading.Tasks.Task<webTOsrv.Calendars> GetTeacherCalendarAsync(int teacherId)
        {
            return base.Channel.GetTeacherCalendarAsync(teacherId);
        }
        
        public bool SetTeacherCalendar(webTOsrv.Calendars cal, int teacherId)
        {
            return base.Channel.SetTeacherCalendar(cal, teacherId);
        }
        
        public System.Threading.Tasks.Task<bool> SetTeacherCalendarAsync(webTOsrv.Calendars cal, int teacherId)
        {
            return base.Channel.SetTeacherCalendarAsync(cal, teacherId);
        }
        
        public void TeacherConfirm(int id, int tid)
        {
            base.Channel.TeacherConfirm(id, tid);
        }
        
        public System.Threading.Tasks.Task TeacherConfirmAsync(int id, int tid)
        {
            return base.Channel.TeacherConfirmAsync(id, tid);
        }
        
        public webTOsrv.AllUsers GetAllTeacher()
        {
            return base.Channel.GetAllTeacher();
        }
        
        public System.Threading.Tasks.Task<webTOsrv.AllUsers> GetAllTeacherAsync()
        {
            return base.Channel.GetAllTeacherAsync();
        }
        
        public string[] GetTeacherReviews(int tid)
        {
            return base.Channel.GetTeacherReviews(tid);
        }
        
        public System.Threading.Tasks.Task<string[]> GetTeacherReviewsAsync(int tid)
        {
            return base.Channel.GetTeacherReviewsAsync(tid);
        }
        
        public webTOsrv.Lessons[] GetAllStudentLessons(int id)
        {
            return base.Channel.GetAllStudentLessons(id);
        }
        
        public System.Threading.Tasks.Task<webTOsrv.Lessons[]> GetAllStudentLessonsAsync(int id)
        {
            return base.Channel.GetAllStudentLessonsAsync(id);
        }
        
        public webTOsrv.Lessons[] GetAllTeacherLessons(int tid)
        {
            return base.Channel.GetAllTeacherLessons(tid);
        }
        
        public System.Threading.Tasks.Task<webTOsrv.Lessons[]> GetAllTeacherLessonsAsync(int tid)
        {
            return base.Channel.GetAllTeacherLessonsAsync(tid);
        }
        
        public void AddLessonForStudent(int sid, string Date, string time)
        {
            base.Channel.AddLessonForStudent(sid, Date, time);
        }
        
        public System.Threading.Tasks.Task AddLessonForStudentAsync(int sid, string Date, string time)
        {
            return base.Channel.AddLessonForStudentAsync(sid, Date, time);
        }
        
        public void UpdateRating(int tid, int rating, string rewiew)
        {
            base.Channel.UpdateRating(tid, rating, rewiew);
        }
        
        public System.Threading.Tasks.Task UpdateRatingAsync(int tid, int rating, string rewiew)
        {
            return base.Channel.UpdateRatingAsync(tid, rating, rewiew);
        }
        
        public bool IsConfirmed(int id)
        {
            return base.Channel.IsConfirmed(id);
        }
        
        public System.Threading.Tasks.Task<bool> IsConfirmedAsync(int id)
        {
            return base.Channel.IsConfirmedAsync(id);
        }
        
        public webTOsrv.UserInfo[] GetTeacherStudents(int tid)
        {
            return base.Channel.GetTeacherStudents(tid);
        }
        
        public System.Threading.Tasks.Task<webTOsrv.UserInfo[]> GetTeacherStudentsAsync(int tid)
        {
            return base.Channel.GetTeacherStudentsAsync(tid);
        }
        
        public int GetTeacherId(int sid)
        {
            return base.Channel.GetTeacherId(sid);
        }
        
        public System.Threading.Tasks.Task<int> GetTeacherIdAsync(int sid)
        {
            return base.Channel.GetTeacherIdAsync(sid);
        }
        
        public void UpdateTeacherId(int sid, int tid)
        {
            base.Channel.UpdateTeacherId(sid, tid);
        }
        
        public System.Threading.Tasks.Task UpdateTeacherIdAsync(int sid, int tid)
        {
            return base.Channel.UpdateTeacherIdAsync(sid, tid);
        }
        
        public void MarkLessonPaid(int id)
        {
            base.Channel.MarkLessonPaid(id);
        }
        
        public System.Threading.Tasks.Task MarkLessonPaidAsync(int id)
        {
            return base.Channel.MarkLessonPaidAsync(id);
        }
        
        public void AddMessageGlobal(string message, int userid, string username, bool IsTeacher)
        {
            base.Channel.AddMessageGlobal(message, userid, username, IsTeacher);
        }
        
        public System.Threading.Tasks.Task AddMessageGlobalAsync(string message, int userid, string username, bool IsTeacher)
        {
            return base.Channel.AddMessageGlobalAsync(message, userid, username, IsTeacher);
        }
        
        public webTOsrv.Chats[] GetAllChatGlobal()
        {
            return base.Channel.GetAllChatGlobal();
        }
        
        public System.Threading.Tasks.Task<webTOsrv.Chats[]> GetAllChatGlobalAsync()
        {
            return base.Channel.GetAllChatGlobalAsync();
        }
        
        public webTOsrv.Chats[] GetChatPrivate(int studentid, int teacherid)
        {
            return base.Channel.GetChatPrivate(studentid, teacherid);
        }
        
        public System.Threading.Tasks.Task<webTOsrv.Chats[]> GetChatPrivateAsync(int studentid, int teacherid)
        {
            return base.Channel.GetChatPrivateAsync(studentid, teacherid);
        }
        
        public void AddMessagePrivate(string message, int studentid, int teacherid, string username)
        {
            base.Channel.AddMessagePrivate(message, studentid, teacherid, username);
        }
        
        public System.Threading.Tasks.Task AddMessagePrivateAsync(string message, int studentid, int teacherid, string username)
        {
            return base.Channel.AddMessagePrivateAsync(message, studentid, teacherid, username);
        }
        
        public bool CheckPaid(int id)
        {
            return base.Channel.CheckPaid(id);
        }
        
        public System.Threading.Tasks.Task<bool> CheckPaidAsync(int id)
        {
            return base.Channel.CheckPaidAsync(id);
        }
        
        public void Pay(webTOsrv.Payment payment)
        {
            base.Channel.Pay(payment);
        }
        
        public System.Threading.Tasks.Task PayAsync(webTOsrv.Payment payment)
        {
            return base.Channel.PayAsync(payment);
        }
        
        public webTOsrv.Payment[] SelectPaymentByPaymentID(int id)
        {
            return base.Channel.SelectPaymentByPaymentID(id);
        }
        
        public System.Threading.Tasks.Task<webTOsrv.Payment[]> SelectPaymentByPaymentIDAsync(int id)
        {
            return base.Channel.SelectPaymentByPaymentIDAsync(id);
        }
        
        public webTOsrv.Payment[] SelectPaymentByTeacherID(int id)
        {
            return base.Channel.SelectPaymentByTeacherID(id);
        }
        
        public System.Threading.Tasks.Task<webTOsrv.Payment[]> SelectPaymentByTeacherIDAsync(int id)
        {
            return base.Channel.SelectPaymentByTeacherIDAsync(id);
        }
        
        public webTOsrv.Calendars[] TeacherSpacialDays(int teacherId)
        {
            return base.Channel.TeacherSpacialDays(teacherId);
        }
        
        public System.Threading.Tasks.Task<webTOsrv.Calendars[]> TeacherSpacialDaysAsync(int teacherId)
        {
            return base.Channel.TeacherSpacialDaysAsync(teacherId);
        }
        
        public webTOsrv.Calendars[] GetTeacherUnavailableDates(int teacherId)
        {
            return base.Channel.GetTeacherUnavailableDates(teacherId);
        }
        
        public System.Threading.Tasks.Task<webTOsrv.Calendars[]> GetTeacherUnavailableDatesAsync(int teacherId)
        {
            return base.Channel.GetTeacherUnavailableDatesAsync(teacherId);
        }
        
        public bool AddUser(string name, string password, string email, string phone, bool admin, int tID)
        {
            return base.Channel.AddUser(name, password, email, phone, admin, tID);
        }
        
        public System.Threading.Tasks.Task<bool> AddUserAsync(string name, string password, string email, string phone, bool admin, int tID)
        {
            return base.Channel.AddUserAsync(name, password, email, phone, admin, tID);
        }
        
        public webTOsrv.Payment[] SelectPaymentByStudentID(int id)
        {
            return base.Channel.SelectPaymentByStudentID(id);
        }
        
        public System.Threading.Tasks.Task<webTOsrv.Payment[]> SelectPaymentByStudentIDAsync(int id)
        {
            return base.Channel.SelectPaymentByStudentIDAsync(id);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/WcfServiceLibrary1/Service1/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Service1Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Service1Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService1,
        }
    }
}
